apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 80         # The service port
      targetPort: 8080 # Container's port
      nodePort: 30090  # Node port (optional)